CREATE TABLE IF NOT EXISTS raamatud(id bigserial primary key , title VARCHAR(200) UNIQUE, status boolean);
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'endymion', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'endymion');
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'hyperion', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'hyperion');
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'olympos', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'olympos');
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'ilium', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'ilium');
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'dune', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'dune');
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'the brothers karmazov', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'ilium');
INSERT INTO RAAMATUD (TITLE, STATUS) SELECT 'better angels of our nature', true WHERE NOT EXISTS ( SELECT TITLE FROM RAAMATUD WHERE TITLE = 'better angels of our nature');

CREATE TABLE IF NOT EXISTS people(id SERIAL, name text, phone bigint, book_id integer REFERENCES raamatud (id));
INSERT INTO PEOPLE (NAME, PHONE) SELECT 'kristi', 5444343 WHERE NOT EXISTS ( SELECT NAME FROM PEOPLE WHERE name = 'kristi');
INSERT INTO PEOPLE (NAME, PHONE) SELECT 'toomas', 6544322 WHERE NOT EXISTS ( SELECT NAME FROM PEOPLE WHERE name = 'toomas');
INSERT INTO PEOPLE (NAME, PHONE) SELECT 'jaan', 434215 WHERE NOT EXISTS ( SELECT NAME FROM PEOPLE WHERE name = 'jaan');
INSERT INTO PEOPLE (NAME, PHONE) SELECT 'viktoria', 889332 WHERE NOT EXISTS ( SELECT NAME FROM PEOPLE WHERE name = 'viktoria');
INSERT INTO PEOPLE (NAME, PHONE) SELECT 'raivo', 478902 WHERE NOT EXISTS ( SELECT NAME FROM PEOPLE WHERE name = 'raivo');